spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring-boot-sample
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update

