server:
  port: 8080
  compression:
    enabled: true
    min-response-size: 2048
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/json,application/xml,application/javascript,image/png