---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  labels:
    app: springbootgwtsample
    version: v1.1.1
  name: springbootgwtsample
  namespace: default
spec:
  # 副本数量
  replicas: 2
  selector:
    matchLabels:
      app: springbootgwtsample
  template:
    metadata:
      labels:
        app: springbootgwtsample
    spec:
      containers:
      - name: springbootgwtsample
        image: panxiaoan/spring-boot-gwt-sample:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 30
          timeoutSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: springbootgwtsample
  labels:
    app: springbootgwtsample
spec:
  type: NodePort
  selector:
    app: springbootgwtsample
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    nodePort: 30233